draw_config:
  shrink_wide_legends: 5
  append_colon_to_layer_header: false
  svg_extra_style: |
    /* Note, it is dumb, but SVG requires that ampersand be escaped (even in CSS!): &amp; */

    /* Nord color scheme */
    :root {
        --dark1: #2e3440;
        --dark2: #3b4252;
        --dark3: #434c5e;
        --dark4: #4c566a;
       --light1: #d8dee9;
       --light2: #e5e9f0;
       --light3: #eceff4;
        --blue1: #8fbcbb;
        --blue2: #88c0d0;
        --blue3: #81a1c1;
        --blue4: #5e81ac;
          --red: #bf616a;
       --orange: #d08770;
       --yellow: #ebcb8b;
        --green: #a3be8c;
       --purple: #b48ead;
    }

    .key rect {
        stroke: var(--light3);
        fill: var(--light3);
    }

    .tap {
        fill: var(--dark1);
        
    }

    .info {
        &amp; .shifted, &amp; .hold {
            fill: var(--dark1)
        }
    }

    .shifted, .hold {
      font-size: 18px;
      fill: var(--blue4);
    }

    .shifted {
        dominant-baseline: hanging;
        text-anchor: end;
        translate: 1.8em 0.5em;
    }

    .hold {
      dominant-baseline: ideographic !important;
      text-anchor: middle;
    }

    .trans, .none, .ghost {
        opacity: 0.8!important;
        &amp; .tap {
            fill: var(--blue2) !important;
        }
    }

    /* Row 2,3,4 (alpha keys) */
    .keypos-23, .keypos-24, .keypos-25, .keypos-26, .keypos-27, .keypos-28, .keypos-29, .keypos-30, .keypos-31, .keypos-32,
    .keypos-35, .keypos-36, .keypos-37, .keypos-38, .keypos-39, .keypos-40, .keypos-41, .keypos-42, .keypos-43, .keypos-44,
    .keypos-47, .keypos-48, .keypos-49, .keypos-50, .keypos-51, .keypos-58, .keypos-59, .keypos-60, .keypos-61, .keypos-62
    {
        &amp; rect {
            fill: var(--light1);
        }
    }

    /* Home keys */
    .keypos-35, .keypos-36, .keypos-37, .keypos-38, .keypos-41, .keypos-42, .keypos-43, .keypos-44
    {
        &amp; rect {
            stroke: var(--purple);
        }
    }

    /* Thumb keys: */
    .keypos-52, .keypos-53, .keypos-54,     .keypos-55, .keypos-56, .keypos-57,
    .keypos-69, .keypos-70, .keypos-71,     .keypos-72, .keypos-73, .keypos-74
    {
       /* TODO? */
    }

    /* Highlight WASD */
    .layer-Gaming {
        /* Home keys */
        &amp; .keypos-25 rect {
            stroke: var(--purple);
        }
        &amp; .keypos-35 rect {
            stroke: var(--light1);
        }
    }

parse_config:
  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans

  raw_binding_map:
    # Custom behavior
    '&smart_lshift': $$mdi:apple-keyboard-shift$$
    '&smart_rshift': $$mdi:apple-keyboard-shift$$
    '&symbols': $$mdi:symbol$$
    '&tog 2': $$mdi:symbol$$
    '&nav': $$mdi:ship-wheel$$
    '&tog 3': $$mdi:ship-wheel$$
    '&tog 4': $$mdi:controller$$

    # Moergo behavior
    '&magic 5 0': $$mdi:creation-outline$$
    '&bt_0':
      type: info
      tap: $$mdi:bluetooth-connect$$
      shifted: 0
    '&bt_1':
      type: info
      tap: $$mdi:bluetooth-connect$$
      shifted: 1
    '&bt_2':
      type: info
      tap: $$mdi:bluetooth-connect$$
      shifted: 2
    '&bt_3':
      type: info
      tap: $$mdi:bluetooth-connect$$
      shifted: 3
    '&bt BT_CLR':
      type: info
      tap: $$mdi:bluetooth-off$$
      hold: Clear
    '&bt BT_CLR_ALL':
      type: info
      tap: $$mdi:bluetooth-off$$
      hold: Clr All
    '&out OUT_USB': $$mdi:usb$$
    '&bootloader': 'Boot'
    '&reset': 'Reset'
    '&sys_reset': 'Reset'

  zmk_keycode_map:
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    RETURN:
      type: enter
      tap: $$mdi:keyboard-return$$
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    LALT: 'Alt' # UK layout
    RALT: 'AltGr' # UK layout
    LCTRL: 'Ctrl'
    RCTRL: 'Ctrl'
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:monitor-dashboard$$
    
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '"' # UK layout
    AT: '"' # UK layout
    HASH: '£' # UK layout
    POUND: '£' # UK layout
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: '#' # UK layout
    BSLH: '#' # UK layout
    PIPE: '~' # UK layout
    NON_US_BSLH: '\'
    NON_US_BACKSLASH: '\'
    PIPE2: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '@' # UK layout
    DQT: '@' # UK layout
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '¬' # UK layout
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'

    N1:
      tap: 1
      shifted: '!'
    N2:
      tap: 2
      shifted: '"' # UK layout
    N3:
      tap: 3
      shifted: '£' # UK layout
    N4:
      tap: 4
      shifted: '$'
    N5:
      tap: 5
      shifted: '%'
    N6:
      tap: 6
      shifted: '^'
    N7:
      tap: 7
      shifted: '&'
    N8:
      tap: 8
      shifted: '*'
    N9:
      tap: 9
      shifted: '('
    N0:
      tap: 0
      shifted: ')'

    KP_NUM: 'Num Lock'
    KP_MINUS: '-'
    KP_PLUS: '+'
    KP_SLASH: '/'
    KP_MULTIPLY: '*'
    KP_EQUAL: '='
    KP_DOT: '.'
    KP_N1: 1
    KP_N2: 2
    KP_N3: 3
    KP_N4: 4
    KP_N5: 5
    KP_N6: 6
    KP_N7: 7
    KP_N8: 8
    KP_N9: 9
    KP_N0: 0

    'LC(LEFT)': $$mdi:chevron-double-left$$
    'LC(RIGHT)': $$mdi:chevron-double-right$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    PAGE_UP: 'Pg Up'
    PAGE_DOWN: 'Pg Down'
    HOME: 'Home'
    END: 'End'
    PSCRN: 'Print'

    C_PP: $$mdi:play-pause$$
    C_PREV: $$mdi:skip-previous$$
    C_NEXT: $$mdi:skip-next$$
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
