parse_config:
  raw_binding_map:
    # Custom behavior
    '&smart_lshift': '$$tabler:arrow-big-up$$'
    '&smart_rshift': '$$tabler:arrow-big-up$$'
    '&symbols': '$$tabler:math-symbols$$'
    '&tog 2': '$$tabler:math-symbols$$'
    '&nav': '$$tabler:wheel$$'
    '&tog 3': '$$tabler:wheel$$'
    '&rgb_ug_status_macro': '$$tabler:star$$'

  zmk_keycode_map:
    RET: '$$tabler:arrow-back$$'
    BACKSPACE: '$$tabler:backspace$$'
    SPACE: '$$tabler:space$$'
    LALT: 'Alt' # UK layout
    RALT: 'AltGr' # UK layout
    LCTRL: 'Ctrl'
    RCTRL: 'Ctrl'
    LGUI: '$$tabler:brand-windows$$'
    TAB: '$$tabler:arrows-left-right$$'
    
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '"' # UK layout
    AT: '"' # UK layout
    HASH: '£' # UK layout
    POUND: '£' # UK layout
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: '#' # UK layout
    BSLH: '#' # UK layout
    PIPE: '~' # UK layout
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '@' # UK layout
    DQT: '@' # UK layout
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '¬' # UK layout
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'

    KP_NUM: 'NumLock'
    KP_MINUS: '-'
    KP_PLUS: '+'
    KP_SLASH: '/'
    KP_MULTIPLY: '*'
    KP_EQUAL: '='
    KP_DOT: '.'
    KP_1: '1'
    KP_2: '2'
    KP_3: '3'
    KP_4: '4'
    KP_5: '5'
    KP_6: '6'
    KP_7: '7'
    KP_8: '8'
    KP_9: '9'
    KP_0: '0'

    LEFT_ARROW: '$$tabler:arrow-narrow-left$$'
    LEFT: '$$tabler:arrow-narrow-left$$'
    RIGHT_ARROW: '$$tabler:arrow-narrow-right$$'
    RIGHT: '$$tabler:arrow-narrow-right$$'
    UP_ARROW: '$$tabler:arrow-narrow-up$$'
    UP: '$$tabler:arrow-narrow-up$$'
    DOWN_ARROW: '$$tabler:arrow-narrow-down$$'
    DOWN: '$$tabler:arrow-narrow-down$$'
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDown'
    HOME: 'Home'
    END: 'End'
    PSCRN: 'Print'

    PP: '$$tabler:player-play$$'
    PREV: '$$tabler:player-skip-back$$'
    NEXT: '$$tabler:player-skip-forward$$'
    MUTE: '$$tabler:volume-3$$'
    VOL_UP: '$$tabler:volume$$'
    VOL_DN: '$$tabler:volume-2$$'
