parse_config:
  raw_binding_map:
    # Custom behavior
    '&smart_lshift': '$$tabler:arrow-big-up$$'
    '&smart_rshift': '$$tabler:arrow-big-up$$'
    '&symbols': '$$tabler:math-symbols$$'
    '&tog 2': '$$tabler:math-symbols$$'
    '&nav': '$$tabler:wheel$$'
    '&tog 3': '$$tabler:wheel$$'
    '&magic 5 0': '$$tabler:star$$'
    '&bt_0': '$$tabler:bluetooth$$ 0'
    '&bt_1': '$$tabler:bluetooth$$ 1'
    '&bt_2': '$$tabler:bluetooth$$ 2'
    '&bt_3': '$$tabler:bluetooth$$ 3'
    '&bt BT_CLR': '$$tabler:bluetooth-x$$'
    '&bt BT_CLR_ALL': '$$tabler:bluetooth-x$$ All'
    '&out OUT_USB': 'USB'
    '&bootloader': 'Bootldr'
    '&reset': 'Reset'
    '&sys_reset': 'Reset'

  zmk_keycode_map:
    RET: '$$tabler:arrow-back$$'
    BACKSPACE: '$$tabler:backspace$$'
    SPACE: '$$tabler:space$$'
    LALT: 'Alt' # UK layout
    RALT: 'AltGr' # UK layout
    LCTRL: 'Ctrl'
    RCTRL: 'Ctrl'
    LSHFT: '$$tabler:arrow-big-up$$'
    RSHFT: '$$tabler:arrow-big-up$$'
    LGUI: '$$tabler:brand-windows$$'
    TAB: '$$tabler:arrows-left-right$$'
    
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '"' # UK layout
    AT: '"' # UK layout
    HASH: '£' # UK layout
    POUND: '£' # UK layout
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: '#' # UK layout
    BSLH: '#' # UK layout
    PIPE: '~' # UK layout
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '@' # UK layout
    DQT: '@' # UK layout
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '¬' # UK layout
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'

    KP_NUM: 'NumLock'
    KP_MINUS: '-'
    KP_PLUS: '+'
    KP_SLASH: '/'
    KP_MULTIPLY: '*'
    KP_EQUAL: '='
    KP_DOT: '.'
    KP_N1: '1'
    KP_N2: '2'
    KP_N3: '3'
    KP_N4: '4'
    KP_N5: '5'
    KP_N6: '6'
    KP_N7: '7'
    KP_N8: '8'
    KP_N9: '9'
    KP_N0: '0'

    LEFT_ARROW: '$$tabler:arrow-narrow-left$$'
    RIGHT_ARROW: '$$tabler:arrow-narrow-right$$'
    'LC(LEFT)': '$$tabler:arrow-move-left$$'
    'LC(RIGHT)': '$$tabler:arrow-move-right$$'
    UP_ARROW: '$$tabler:arrow-narrow-up$$'
    UP: '$$tabler:arrow-narrow-up$$'
    DOWN_ARROW: '$$tabler:arrow-narrow-down$$'
    DOWN: '$$tabler:arrow-narrow-down$$'
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDown'
    HOME: 'Home'
    END: 'End'
    PSCRN: 'Print'

    C_PP: '$$tabler:player-play$$'
    C_PREV: '$$tabler:player-skip-back$$'
    C_NEXT: '$$tabler:player-skip-forward$$'
    C_MUTE: '$$tabler:volume-3$$'
    C_VOL_UP: '$$tabler:volume$$'
    C_VOL_DN: '$$tabler:volume-2$$'
