name: Draw keymaps
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - "**.lock"
      - "drawer/**"
      - "config/**"

jobs:
  draw:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow CI to write commits to the repo

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Set to 2 if amending, or 1 if creating a new commit
          fetch-depth: 1
          submodules: recursive

      - name: Install nix
        uses: cachix/install-nix-action@v25
      - name: Setup nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Draw keymaps
        run: nix run .#draw

      # TODO print to $GITHUB_STEP_SUMMARY
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Draw] ${{ github.event.head_commit.message || '(Manually triggered)' }}"
          file_pattern: img/**

