name: Update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 10 * * sat' # every Saturday at 10am

permissions:
  contents: write
  pull-requests: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-labels: dependencies
          pr-assignees: MattSturgeon
      - name: Summary
        run: |
          base="${{ github.server_url }}/${{ github.repository }}"
          num="${{ steps.update.outputs.pull-request-number }}"
          action="${{ steps.update.outputs.pull-request-operation }}"
          url="${base}/pull/${num}"
          pr="#${num}"

          # stdout
          echo "${pr} was ${action}."

          # summary
          echo "## Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "[${pr}](${url}) was ${action}." >> $GITHUB_STEP_SUMMARY

